### ISSUE TITLE
add flask middleware to bestie and expose "response time" metric

### ISSUE THREAD

**Issue by skattoju** [opdev/l5-operator-demo#49]

**Comment by makon57** [comment]
Following these documentation [Prometheus & Grafana](https://medium.com/swlh/generate-and-track-metrics-for-flask-api-applications-using-prometheus-and-grafana-55ddd39866f0) and [Prometheus Metrics](https://dev.to/camptocamp-ops/implement-prometheus-metrics-in-a-flask-application-p18) to implement metrics into Flask API application.

**Comment by makon57** [comment]
added flask app metrics via prometheus_client and added /metrics route for generate_latest default metrics
new image "quay.io/mkong/bestiev2:1.3"
