### ISSUE TITLE
annotation is missing

### ISSUE THREAD

**Issue by rocrisp** [opdev/l5-operator-demo#55]
I get the following error when I apply the CR.
roc apply -f config/samples/pets_v1_bestie.yaml 
Warning: resource besties/bestie is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by oc apply. oc apply should only be used on resources created declaratively by either oc create --save-config or oc apply. The missing annotation will be patched automatically.
bestie.pets.bestie.com/bestie configured

**Comment by skattoju** [comment]
not a bug
